# Reduce logging level to make sure the application works with SAM local
# https://github.com/aws/serverless-java-container/issues/134
server:
  port: 8080
logging:
  level:
    root: WARN
    org.springframework.web: ERROR
    com.amazonaws: ERROR
    # Add specific logging for your ClamAV scanner
    k.g.g.v.config.ClamAvScanner: DEBUG

aws:
  s3:
    endpoint: http://localstack:4566  # Change to localstack
    access-key-id: test
    access-key-secret: test
    region-name: ap-southeast-1
    buckets:
      quarantine: quarantine-bucket
      clean: clean-bucket
    development: true


clamav:
  host: scan
  port: 3310
  timeout: 60000